### ISSUE TITLE
Fix use of deprecated gradle features

### ISSUE THREAD

**Issue by stuebingerb** [stuebingerb/KGraphQL#48]
```
> Task :kgraphql:test
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.10.2/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
```

**Comment by stuebingerb** [comment]
Seems like there are 2 options:

1. Explicitly declare the junit platform launcher as dependency:
    ```
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    ```
2. Migrate to test suites: https://docs.gradle.org/8.10.2/userguide/jvm_test_suite_plugin.html

**Comment by mervyn-mccreight** [comment]
I'd favor 2, so we can e.g. easily test compatibility of the ktor integration with different major versions (2.x and 3.x would make sense currently IMO).

Using the test-suite plugin takes away some usual boilerplate needed for something like this (like configuring separate source-sets).
