### ISSUE TITLE
Print schema as SDL

### ISSUE THREAD

**Issue by stuebingerb** [stuebingerb/KGraphQL#79]
Copied from https://github.com/aPureBase/KGraphQL/issues/14

I would like to be able to print the schema as human-readable schema definition language (SDL). Not sure if there is a common way of exposing it but I'm thinking about returning it from `GET /<graphql-endpoint>?schema` when introspection is enabled.

**Comment by mervyn-mccreight** [comment]
I'd stick to implement returning the schema as sdl as effectively a string in the core library and think about if or how to integrate it into the ktor integration afterwards.
